# Generated by Django 4.0.4 on 2022-05-23 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingclass',
            name='list_classes',
        ),
        migrations.AddField(
            model_name='listclasses',
            name='training_class',
            field=models.ForeignKey(db_column='id_класса', default='', on_delete=django.db.models.deletion.CASCADE, to='diplom.trainingclass', verbose_name='Список классов'),
        ),
    ]
